default_platform(:ios)

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :update_metadata do
    deliver(
      submit_for_review: false,
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true
    )
  end
end
